os: linux
language: python # build system
python: "3.7"
dist: xenial
compiler:
  - gcc
install:
  - pip install conan
  - conan user
script:
  - conan install .
  - cmake . -G "Unix Makefiles" && cmake --build .
